apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: echo
    visualize: "true"
  name: echo-controller
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: echo
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kidcontrol2-b938c/echo:v50
        name: echo
        ports:
        - name: echo
          containerPort: 5701
